<<<<<<< HEAD
name: Unit Testing - Unity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
=======
name: Unit Testing - Unity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
>>>>>>> c80e01c07c3740a82133b5ea9a20a168220843fe
      run: make -C 3_Implementation/ test